agents:
  - name: code_fix_agent
    config_path: code_fix_agent/config.yaml
  - name: code_optimizer_agent
    config_path: code_optimizer_agent/config.yaml
  - name: code_review_agent
    config_path: code_review_agent/config.yaml
  - name: code_split_agent
    config_path: code_split_agent/config.yaml
  - name: code_write_agent
    config_path: code_write_agent/config.yaml
  - name: design_fix_agent
    config_path: design_fix_agent/config.yaml
  - name: design_update_agent
    config_path: design_update_agent/config.yaml
  - name: design_write_agent
    config_path: design_write_agent/config.yaml
  - name: test_case_generator_agent
    config_path: test_case_generator_agent/config.yaml
  - name: zoltraak_agent
    config_path: zoltraak_agent/config.yaml
