agent_definition:
  agent_name: "design_write_agent"
  agent_type: tool_calling
  agent_role: |
    ソフトウェア設計文書を作成する作業をお願いします。
    単独のソースファイルでは実現できないような複雑なプログラムを作成する場合に使用します。
    ソースファイルの相対パス、概要、関数名の一覧を集約し、Markdown形式で整理します。
    これにより複雑なプログラムをスムーズに作成・修正できるようにすることがねらいです。

  agent_expected_output: |
    Markdown形式の文書「software_design.md」を出力してください。以下のフォーマットに従ってください：

    # ソフトウェア設計文書

    ## ソースファイル一覧
    - **相対パス**: `src/module1.py`
      - **概要**: モジュール1の主機能を実装
      - **関数名**:
        - `function_a`
        - `function_b`
    - **相対パス**: `src/module2.py`
      - **概要**: モジュール2の補助機能を実装
      - **関数名**:
        - `function_c`
        - `function_d`
    - **相対パス**: `tests/test_module1.py`
      - **概要**: モジュール1のテストケースを含む
      - **関数名**:
        - `test_function_a`
  agent_acceptable_task_description: |
    新規プロジェクトや初期設計段階で、ソフトウェアの全体設計を把握するために、ソースファイルの相対パス、概要、および関数名の一覧を整理した文書を作成するタスクです。
  agent_tools: |
    terminal
    zoltraak_design
